set_property SRC_FILE_INFO {cfile:{C:/Users/tongplw/Desktop/Vivado/Lab06/Lab06.srcs/constrs_1/new/Basys 3 Master.xdc} rfile:{../../../Lab06.srcs/constrs_1/new/Basys 3 Master.xdc} id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property src_info {type:XDC file:1 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B18 [get_ports RsRx]
set_property src_info {type:XDC file:1 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A18 [get_ports RsTx]
